config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, only: [:new]
  devise_for :users

  get "/users/sign_out", to: "home#destroy"
  get "/profil/:user_name", to: "profil#index"

  resources :posts

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :posts
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_and_belongs_to_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :city
	has_and_belongs_to_many :genres
	mount_uploader :image, PostUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts
  mount_uploader :image, UserUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery
	before_action :configure_devise_parametres, if: :devise_controller?
  	layout :layout_by_controller


    def layout_by_controller
        if devise_controller? && resource_name == :user
            "devise"
        end
  	end

  	def configure_devise_parametres
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :image)}
	end

    def after_sign_in_path_for(resource)
        posts_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout 'application'
	
	def index
		@posts = Post.all
		@test = Post.all.count
	end

	def destroy
		sign_out(current_user)
		redirect_to root_path
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout 'post', except: [:new, :edit]
    layout 'new_post', only: [:new, :edit]
    before_action :user_connect, except: [:show]

    def index
    end

    def new

    end

    def create
        Post.create(permit_params)

        @list = params["list"]

        @list.each do |cle, val|
            if val == "yes"
                Post.last.genres << Genre.where(list: cle)
            end
        end

        redirect_to posts_path
    end

    def edit
    end

    def show
    end

    def update
    end

    def destroy
    end

 private

    def user_connect
        if user_signed_in?
            @post = Post.new
        else
            redirect_to new_user_session_path
        end         
    end

    def permit_params
        params.require(:post).permit(:title, :address, :date_limite, :hour, :description, :price, :image, :user_id, :city_id)
    end

end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/home/index.html.erb
	<!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header header">

        <div class="header__logo">
            <a class="logo" href="<% root_path %>">
                <img src="home/images/LOGO.png" alt="Homepage">
            </a>
        </div> <!-- end header__logo -->

        <a class="header__search-trigger" href="#"></a>

        <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>
        <nav class="header__nav-wrap">

            <h2 class="header__nav-heading h6">Menu</h2>

            <ul class="header__nav">
                <li class="has-children">
                    <a href="#0" title="">Province</a>
                    <ul class="sub-menu">
                    	<li><a href="#">Antananarivo</a></li>
                        <li><a href="#">Antsiranana</a></li>
                        <li><a href="#">Mahajanga</a></li>
                        <li><a href="#">Toamasina</a></li>
                        <li><a href="#">Fianarantsoa</a></li>
                        <li><a href="#">Toliara</a></li>
                    </ul>
                <li class="has-children">
                    <a href="#0" title="">Tout les evenemets</a>
                    <ul class="sub-menu">
                        <li><a href="#">Sport</a></li>
                        <li><a href="#">Cabaret</a></li>
                        <li><a href="#">Spectacle</a></li>
                        <li><a href="#">Soirée</a></li>
                        <li><a href="#">Festival</a></li>
                        <li><a href="#">Scolaire</a></li>
                        <li><a href="#">Conference</a></li>
                        <li><a href="#">Foire</a></li>
                        <li><a href="#">Salon</a></li>
                        <li><a href="#">Teatre</a></li>
                        <li><a href="#">Evangelique</a></li>
                        <li><a href="#">Balle</a></li>
                    </ul>
                </li>

                <% if(user_signed_in?) %>
                <li class="has-children">
                    <%if current_user.image?%>
                        <a href="#0" title=""><img src="<%= current_user.image_url %>" style="border-radius: 100%; width: 25px; height: 25px; margin-bottom: -10px;"></a>
                    <% else %>
                        <a href="#0" title=""><img src="users/images/user-icon.png" style="border-radius: 100%; width: 25px; height: 25px; margin-bottom: -10px;"></a>
                    <% end %>
                    <ul class="sub-menu">
                        <li><a href="/<%= current_user.username%>"><%= current_user.username.capitalize %></a> </li>
                        <li><a href="<%= posts_path%>">Mes publications</a></li>
                    <li><%= link_to "se deconecter", destroy_user_session_path, method: :delete, style: "color: #DCD850; font-size: 15px" %></li>
                    </ul>
                </li>
                <% else %>
                    <li><%= link_to "se connecter", new_user_session_path, style: "color: #15c4d4; font-size: 18px" %></li>
                    <li><%= link_to "s'inscrire", new_user_registration_path(@user), style: "color: #68de4d; font-size: 16px" %></li>
                <% end %>

            </ul>

            <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

        </nav>

    </header>

<% if @test != 0 %>

    <section class="s-featured">
        <div class="row">
            <div class="col-full">

                <div class="featured-slider featured" data-aos="zoom-in">

                    <div class="featured__slide">
                        <div class="entry">

                            <div class="entry__background" style="background-image:url('<%= @posts[0].image_url%>');"></div>
                            
                            <div class="entry__content">
                                <span class="entry__category"><a href="#0"><%=@posts[0].genres.first.list%></a></span>

                                <h1><a href="#0" title=""><%=@posts[0].title%></a></h1>

                                <div class="entry__info">
                                    <a href="/profil/<%=@posts[0].user.username%>" class="entry__profile-pic">
                                        <% if @posts[0].user.image?%>
                                            <img class="avatar" src="<%=@posts[0].user.image_url%>" alt="">
                                        <%else%>
                                            <img class="avatar" src="images/icons/user-icon.png" alt="">
                                        <%end%>                                           
                                    </a>
                                    <ul class="entry__meta">
                                        <li><a href="#0"><%=@posts[0].address.capitalize%></a></li>
                                        <% d0 = @posts[0].date_limite.to_formatted_s(:rfc822) %>
                                        <li><%=d0[5..15] +' à '+ @posts[0].hour%></li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->
                            
                        </div> <!-- end entry -->
                    </div> <!-- end featured__slide -->

                    <div class="featured__slide">

                        <div class="entry">

                            <div class="entry__background" style="background-image:url('<%= @posts[1].image_url%>');"></div>
                            
                            <div class="entry__content">
                                <span class="entry__category"><a href="#0"><%=@posts[1].genres.first.list%></a></span>

                                <h1><a href="#0" title=""><%=@posts[1].title%></a></h1>

                                <div class="entry__info">
                                    <a href="/profil/<%=@posts[1].user.username%>" class="entry__profile-pic">
                                        <% if @posts[1].user.image?%>
                                            <img class="avatar" src="<%=@posts[1].user.image_url%>" alt="">
                                        <%else%>
                                            <img class="avatar" src="images/icons/user-icon.png" alt="">
                                        <%end%> 
                                    </a>

                                    <ul class="entry__meta">
                                        <li><a href="#0"><%=@posts[1].address.capitalize%></a></li>
                                        <% d1 = @posts[1].date_limite.to_formatted_s(:rfc822) %>
                                        <li><%=d1[5..15] +' à '+ @posts[1].hour%></li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->
                            
                        </div> <!-- end entry -->

                    </div> <!-- end featured__slide -->

                    <div class="featured__slide">

                        <div class="entry">

                            <div class="entry__background" style="background-image:url('<%= @posts[2].image_url%>');"></div>

                            <div class="entry__content">
                                <span class="entry__category"><a href="#0"><%=@posts[2].genres.first.list%></a></span>

                                <h1><a href="#0" title=""><%=@posts[2].title%></a></h1>

                                <div class="entry__info">
                                    <a href="/profil/<%=@posts[2].user.username%>" class="entry__profile-pic">
                                        <% if @posts[2].user.image?%>
                                            <img class="avatar" src="<%=@posts[2].user.image_url%>" alt="">
                                        <%else%>
                                            <img class="avatar" src="images/icons/user-icon.png" alt="">
                                        <%end%> 
                                    </a>

                                    <ul class="entry__meta">
                                        <li><a href="#0"><%=@posts[2].address.capitalize%></a></li>
                                        <% d2 = @posts[2].date_limite.to_formatted_s(:rfc822) %>
                                        <li><%=d2[5..15] +' à '+ @posts[2].hour%></li>
                                    </ul>
                                </div>
                            </div> <!-- end entry__content -->

                        </div> <!-- end entry -->

                    </div> <!-- end featured__slide -->
                    
                </div> <!-- end featured -->

            </div> <!-- end col-full -->
        </div>
    </section> <!-- end s-featured -->

<!----------------------------------------------------------------------------------------------------------------------->
    <section class="s-content">
        
        <div class="row entries-wrap wide">
            <div class="entries">

                <% @posts.each do |post| %>

                <article class="col-block">
                    
                    <div class="item-entry" data-aos="zoom-in">
                        <div class="item-entry__thumb">
                            <a href="#" class="item-entry__thumb-link">
                                <img src="<%= post.image_url(:image_400)%>" 
                                     srcset="<%= post.image_url(:image_400)%> 1x, <%= post.image_url(:image_900)%> 2x" alt="">
                            </a>
                        </div>
        
                        <div class="item-entry__text">    
                            <div class="item-entry__cat">
                                <a href="category.html"><%=post.genres.first.list%></a> 
                            </div>
    
                            <h1 class="item-entry__title"><a href="single-standard.html"><%=post.title%></a></h1>
                                
                            <div class="item-entry__date">
                                <% d2 = post.date_limite.to_formatted_s(:rfc822) %>
                                <a href="#0"><%=post.address.capitalize%> <%=d2[5..15] +' à '+ @posts[0].hour%></a>
                            </div>
                        </div>
                    </div> <!-- item-entry -->

                </article> <!-- end article -->

            <% end %><!------------------end each--------------------->
                
            </div> <!-- end entries -->
        </div> <!-- end entries-wrap -->

    </section> <!-- end s-content -->

<%else%>
    
    <br><br><br><br><center><h2>Pas d'evenement a afficher</h2></center><br>
    <center><h2><%= link_to "Connecter", new_user_session_path, style: "color: #15c4d4; font-size: 30px" %> vous pour poster des evenements <br>sur nosyevents</h2></center><br>

<% end %>





    <!-- s-foote
    =========================================================================================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">
                
                <div class="col-six tab-full s-footer__about">
                        
                    <h4>A propos de nosyevents</h4>

                    <p>.....................................................................................
                        .......................................................................................
                        .............................................................................................</p>

                </div> <!-- end s-footer__about -->

                <div class="col-six tab-full s-footer__subscribe">
                        
                    <h4>Des problemes sur nosyevents?</h4>

                    <p>Envoyer nous un <a href="mailto:nosyevents@gmail.com">Email</a> pour vous aidez a resoudre le probleme</p><br>
                    <a href="#">Comment utiliser ce site</a><br>

                </div> <!-- end s-footer__subscribe -->

            </div>
        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">

                <div class="col-six">
                    <ul class="footer-social">
                        <li>
                            <a href="#0"><i class="fab fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#0"><i class="fab fa-twitter"></i></a>
                        </li>

                        <li>
                            <a href="#0"><i class="fab fa-youtube"></i></a>
                        </li>
                    </ul>
                </div>

                <div class="col-six">
                    <div class="s-footer__copyright">
                        <span>
                            Copyright Nosyevents 2020

                        </span>
                    </div>
                </div>
                
            </div>
        </div> <!-- end s-footer__bottom -->

        <div class="go-top">
            <a class="smoothscroll" title="Back to Top" href="#top"></a>
        </div>

    </footer> <!-- end s-footer -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>

    <meta charset="utf-8">
    <title>Nosyevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>



    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/png" href="images/icons/nosyevents.ico"/>


    <link rel="stylesheet" href="home/css/base.css">
    <link rel="stylesheet" href="home/css/vendor.css">
    <link rel="stylesheet" href="home/css/main.css">

    <script src="home/js/modernizr.js"></script>
  </head>

  <body id="top">
    <p class="notice"><%= notice %></p>
    <%= yield %>

    <script src="home/js/jquery-3.2.1.min.js"></script>
    <script src="home/js/plugins.js"></script>
    <script src="home/js/main.js"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosyevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/png" href="images/icons/nosyevents.ico"/>



  </head>

  <body>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
    
  <%= javascript_pack_tag 'users', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/new_post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosyevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--===============================================================================================-->  
  <link rel="icon" type="image/png" href="images/icons/nosyevents.ico"/>
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->  
  <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="css/util.css">
  <link rel="stylesheet" type="text/css" href="css/main.css">

  </head>

  <body id="top">

    <%= yield %>

<!--===============================================================================================-->  
  <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
  <script src="vendor/bootstrap/js/popper.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
  <script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
  <script src="js/main.js"></script>
    
  </body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosyevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/png" href="images/icons/nosyevents.ico"/>

    <link rel="stylesheet" href="home/css/base.css">
    <link rel="stylesheet" href="home/css/vendor.css">
    <link rel="stylesheet" href="home/css/main.css">

    <script src="home/js/modernizr.js"></script>

  </head>

  <body id="top">

    <%= yield %>

    <script src="home/js/jquery-3.2.1.min.js"></script>
    <script src="home/js/plugins.js"></script>
    <script src="home/js/main.js"></script>
    
  </body>
</html>

app/views/layouts/profil.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosyevents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/png" href="images/icons/nosyevents.ico"/>


  </head>

  <body>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
    
  <%= javascript_pack_tag 'users', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header header">

        <div class="header__logo">
            <a class="logo" href="/">
                <img src="home/images/LOGO.png" alt="Homepage">
            </a>
        </div> <!-- end header__logo -->

        <a class="header__search-trigger" href="#"></a>

        <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>
        <nav class="header__nav-wrap">

            <h2 class="header__nav-heading h6">Menu</h2>

            <ul class="header__nav">
                <li class="has-children">
                    <a href="#0" title="">Province</a>
                    <ul class="sub-menu">
                        <li><a href="category.html">Antananarivo</a></li>
                        <li><a href="category.html">Antsiranana</a></li>
                        <li><a href="category.html">Mahajanga</a></li>
                        <li><a href="category.html">Toamasina</a></li>
                        <li><a href="category.html">Fianarantsoa</a></li>
                        <li><a href="category.html">Toliara</a></li>
                    </ul>
                <li class="has-children">
                    <a href="#0" title="">Tout les evenemets</a>
                    <ul class="sub-menu">
                        <li><a href="category.html">Sport</a></li>
                        <li><a href="category.html">Cabaret</a></li>
                        <li><a href="category.html">Spectacle</a></li>
                        <li><a href="category.html">Soirée</a></li>
                        <li><a href="category.html">Festival</a></li>
                        <li><a href="category.html">Scolaire</a></li>
                        <li><a href="category.html">Lifestyle</a></li>
                        <li><a href="category.html">Foire</a></li>
                        <li><a href="category.html">Salon</a></li>
                        <li><a href="category.html">Teatre</a></li>
                        <li><a href="category.html">Evangelique</a></li>
                        <li><a href="category.html">Balle</a></li>
                    </ul>
                </li>

                <% if(user_signed_in?) %>
                <li class="has-children">
                    <%if current_user.image?%>
                        <a href="#0" title=""><img src="<%= current_user.image %>" style="border-radius: 100%; width: 25px; height: 25px; margin-bottom: -10px;"></a>
                    <% else %>
                        <a href="#0" title=""><img src="users/images/user-icon.png" style="border-radius: 100%; width: 25px; height: 25px; margin-bottom: -10px;"></a>
                    <% end %>
                    <ul class="sub-menu">
                        <li><a href="/users/<%= current_user.username%>"><%= current_user.username.capitalize %></a> </li>
                        <li><a href="<%= posts_path%>">Mes publications</a></li>
                    <li><%= link_to "se deconecter", destroy_user_session_path, method: :delete, style: "color: #DCD850; font-size: 15px" %></li>
                    </ul>
                </li>
                <% else %>
                    <li><%= link_to "se connecter", new_user_session_path, style: "color: #15c4d4; font-size: 18px" %></li>
                    <li><%= link_to "s'inscrire", new_user_registration_path(@user), style: "color: #68de4d; font-size: 16px" %></li>
                <% end %>

            </ul>

            <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

        </nav>

    </header>




 










<h1>Page de tout vo publication</h1>

<%= link_to "Poster un nouvelle evenement", new_post_path %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/profil/index.html.erb
<h1>Profil#index</h1>
<p>Find me in app/views/profil/index.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>